### PR TITLE
Fix Errors (#53)

### LINKED ISSUE #53: Fix errors so they provide more information
Now when for example `Some(null);` is called the only information we get with thrown error is `"Illegal state exception"` and stack. Would be nice if it informed that it's Monet error and that it's connected with Maybe :)

### PR DESCRIPTION
**Pull request by ulfryk**
…and also:
- add ESLint with bunch of strict rules
- remove some unused code
- cleanup tests

This one fixes #53

### CODE REVIEW

File: dist/monet.js [hunk 1]
```diff
@@ -1047,9 +1009,9 @@
         };
     }
     function addFunctorOps(type) {
-        if (type.prototype.map == null) {
+        if (!type.prototype.map) {
```
Comment (kpudlik) [inline dist/monet.js]: How about `if(!isFuncton(type.prototype.map)) {` ? It will follow conventions from methods above (I guess).
